name: 'sampctl Action Windows'
description: 'Setup sampctl in the environment'
branding:
  icon: truck
  color: orange
inputs:
  version:
    description: 'Version of sampctl'
    required: true
    default: '1.11.0'
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/Southclaws/sampctl/releases/download/${{ inputs.version }}/sampctl_${{ inputs.version }}_windows_amd64.tar.gz" -OutFile "sampctl.tar.gz"
        New-Item -ItemType Directory -Path "$env:USERPROFILE\sampctl" -Force
        tar -xzf sampctl.tar.gz -C "$env:USERPROFILE\sampctl"
        $env:Path += ";$env:USERPROFILE\sampctl"
